apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: dat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dat
  template:
    metadata:
      labels:
        app: dat
    spec:
      containers:
      - name: dun
        image: tamilmaran787/dun 
        ports:
        - containerPort: 8080

        
        
        
